/**
 * GENERATED — do not edit by hand.
 * Source: data/india_districts_lgd.csv (LGD codes).
 * Regenerate: npm run districts:generate
 * Entries: 784
 */
export interface DistrictInfo {
  code: number;
  name: string;
  stateName: string;
  stateShort: string;
}

/** LGD district code → info. Codes are globally unique across states. */
export const DISTRICTS: Record<number, DistrictInfo> = {
  1: { code: 1, name: "Anantnag", stateName: "Jammu And Kashmir", stateShort: "JK" },
  2: { code: 2, name: "Budgam", stateName: "Jammu And Kashmir", stateShort: "JK" },
  3: { code: 3, name: "Baramulla", stateName: "Jammu And Kashmir", stateShort: "JK" },
  4: { code: 4, name: "Doda", stateName: "Jammu And Kashmir", stateShort: "JK" },
  5: { code: 5, name: "Jammu", stateName: "Jammu And Kashmir", stateShort: "JK" },
  6: { code: 6, name: "Kargil", stateName: "Ladakh", stateShort: "LA" },
  7: { code: 7, name: "Kathua", stateName: "Jammu And Kashmir", stateShort: "JK" },
  8: { code: 8, name: "Kupwara", stateName: "Jammu And Kashmir", stateShort: "JK" },
  9: { code: 9, name: "Leh Ladakh", stateName: "Ladakh", stateShort: "LA" },
  10: { code: 10, name: "Poonch", stateName: "Jammu And Kashmir", stateShort: "JK" },
  11: { code: 11, name: "Pulwama", stateName: "Jammu And Kashmir", stateShort: "JK" },
  12: { code: 12, name: "Rajouri", stateName: "Jammu And Kashmir", stateShort: "JK" },
  13: { code: 13, name: "Srinagar", stateName: "Jammu And Kashmir", stateShort: "JK" },
  14: { code: 14, name: "Udhampur", stateName: "Jammu And Kashmir", stateShort: "JK" },
  15: { code: 15, name: "Bilaspur", stateName: "Himachal Pradesh", stateShort: "HP" },
  16: { code: 16, name: "Chamba", stateName: "Himachal Pradesh", stateShort: "HP" },
  17: { code: 17, name: "Hamirpur", stateName: "Himachal Pradesh", stateShort: "HP" },
  18: { code: 18, name: "Kangra", stateName: "Himachal Pradesh", stateShort: "HP" },
  19: { code: 19, name: "Kinnaur", stateName: "Himachal Pradesh", stateShort: "HP" },
  20: { code: 20, name: "Kullu", stateName: "Himachal Pradesh", stateShort: "HP" },
  21: { code: 21, name: "Lahaul And Spiti", stateName: "Himachal Pradesh", stateShort: "HP" },
  22: { code: 22, name: "Mandi", stateName: "Himachal Pradesh", stateShort: "HP" },
  23: { code: 23, name: "Shimla", stateName: "Himachal Pradesh", stateShort: "HP" },
  24: { code: 24, name: "Sirmaur", stateName: "Himachal Pradesh", stateShort: "HP" },
  25: { code: 25, name: "Solan", stateName: "Himachal Pradesh", stateShort: "HP" },
  26: { code: 26, name: "Una", stateName: "Himachal Pradesh", stateShort: "HP" },
  27: { code: 27, name: "Amritsar", stateName: "Punjab", stateShort: "PB" },
  28: { code: 28, name: "Bathinda", stateName: "Punjab", stateShort: "PB" },
  29: { code: 29, name: "Faridkot", stateName: "Punjab", stateShort: "PB" },
  30: { code: 30, name: "Fatehgarh Sahib", stateName: "Punjab", stateShort: "PB" },
  31: { code: 31, name: "Ferozepur", stateName: "Punjab", stateShort: "PB" },
  32: { code: 32, name: "Gurdaspur", stateName: "Punjab", stateShort: "PB" },
  33: { code: 33, name: "Hoshiarpur", stateName: "Punjab", stateShort: "PB" },
  34: { code: 34, name: "Jalandhar", stateName: "Punjab", stateShort: "PB" },
  35: { code: 35, name: "Kapurthala", stateName: "Punjab", stateShort: "PB" },
  36: { code: 36, name: "Ludhiana", stateName: "Punjab", stateShort: "PB" },
  37: { code: 37, name: "Mansa", stateName: "Punjab", stateShort: "PB" },
  38: { code: 38, name: "Moga", stateName: "Punjab", stateShort: "PB" },
  39: { code: 39, name: "Sri Muktsar Sahib", stateName: "Punjab", stateShort: "PB" },
  40: { code: 40, name: "Shahid Bhagat Singh Nagar", stateName: "Punjab", stateShort: "PB" },
  41: { code: 41, name: "Patiala", stateName: "Punjab", stateShort: "PB" },
  42: { code: 42, name: "Rupnagar", stateName: "Punjab", stateShort: "PB" },
  43: { code: 43, name: "Sangrur", stateName: "Punjab", stateShort: "PB" },
  44: { code: 44, name: "Chandigarh", stateName: "Chandigarh", stateShort: "CH" },
  45: { code: 45, name: "Almora", stateName: "Uttarakhand", stateShort: "UK" },
  46: { code: 46, name: "Bageshwar", stateName: "Uttarakhand", stateShort: "UK" },
  47: { code: 47, name: "Chamoli", stateName: "Uttarakhand", stateShort: "UK" },
  48: { code: 48, name: "Champawat", stateName: "Uttarakhand", stateShort: "UK" },
  49: { code: 49, name: "Dehradun", stateName: "Uttarakhand", stateShort: "UK" },
  50: { code: 50, name: "Haridwar", stateName: "Uttarakhand", stateShort: "UK" },
  51: { code: 51, name: "Nainital", stateName: "Uttarakhand", stateShort: "UK" },
  52: { code: 52, name: "Pauri Garhwal", stateName: "Uttarakhand", stateShort: "UK" },
  53: { code: 53, name: "Pithoragarh", stateName: "Uttarakhand", stateShort: "UK" },
  54: { code: 54, name: "Rudraprayag", stateName: "Uttarakhand", stateShort: "UK" },
  55: { code: 55, name: "Tehri Garhwal", stateName: "Uttarakhand", stateShort: "UK" },
  56: { code: 56, name: "Udham Singh Nagar", stateName: "Uttarakhand", stateShort: "UK" },
  57: { code: 57, name: "Uttarkashi", stateName: "Uttarakhand", stateShort: "UK" },
  58: { code: 58, name: "Ambala", stateName: "Haryana", stateShort: "HR" },
  59: { code: 59, name: "Bhiwani", stateName: "Haryana", stateShort: "HR" },
  60: { code: 60, name: "Faridabad", stateName: "Haryana", stateShort: "HR" },
  61: { code: 61, name: "Fatehabad", stateName: "Haryana", stateShort: "HR" },
  62: { code: 62, name: "Gurugram", stateName: "Haryana", stateShort: "HR" },
  63: { code: 63, name: "Hisar", stateName: "Haryana", stateShort: "HR" },
  64: { code: 64, name: "Jhajjar", stateName: "Haryana", stateShort: "HR" },
  65: { code: 65, name: "Jind", stateName: "Haryana", stateShort: "HR" },
  66: { code: 66, name: "Kaithal", stateName: "Haryana", stateShort: "HR" },
  67: { code: 67, name: "Karnal", stateName: "Haryana", stateShort: "HR" },
  68: { code: 68, name: "Kurukshetra", stateName: "Haryana", stateShort: "HR" },
  69: { code: 69, name: "Mahendragarh", stateName: "Haryana", stateShort: "HR" },
  70: { code: 70, name: "Panchkula", stateName: "Haryana", stateShort: "HR" },
  71: { code: 71, name: "Panipat", stateName: "Haryana", stateShort: "HR" },
  72: { code: 72, name: "Rewari", stateName: "Haryana", stateShort: "HR" },
  73: { code: 73, name: "Rohtak", stateName: "Haryana", stateShort: "HR" },
  74: { code: 74, name: "Sirsa", stateName: "Haryana", stateShort: "HR" },
  75: { code: 75, name: "Sonipat", stateName: "Haryana", stateShort: "HR" },
  76: { code: 76, name: "Yamunanagar", stateName: "Haryana", stateShort: "HR" },
  77: { code: 77, name: "Central", stateName: "Delhi", stateShort: "DL" },
  78: { code: 78, name: "East", stateName: "Delhi", stateShort: "DL" },
  79: { code: 79, name: "New Delhi", stateName: "Delhi", stateShort: "DL" },
  80: { code: 80, name: "North", stateName: "Delhi", stateShort: "DL" },
  81: { code: 81, name: "North East", stateName: "Delhi", stateShort: "DL" },
  82: { code: 82, name: "North West", stateName: "Delhi", stateShort: "DL" },
  83: { code: 83, name: "South", stateName: "Delhi", stateShort: "DL" },
  84: { code: 84, name: "South West", stateName: "Delhi", stateShort: "DL" },
  85: { code: 85, name: "West", stateName: "Delhi", stateShort: "DL" },
  86: { code: 86, name: "Ajmer", stateName: "Rajasthan", stateShort: "RJ" },
  87: { code: 87, name: "Alwar", stateName: "Rajasthan", stateShort: "RJ" },
  88: { code: 88, name: "Banswara", stateName: "Rajasthan", stateShort: "RJ" },
  89: { code: 89, name: "Baran", stateName: "Rajasthan", stateShort: "RJ" },
  90: { code: 90, name: "Barmer", stateName: "Rajasthan", stateShort: "RJ" },
  91: { code: 91, name: "Bharatpur", stateName: "Rajasthan", stateShort: "RJ" },
  92: { code: 92, name: "Bhilwara", stateName: "Rajasthan", stateShort: "RJ" },
  93: { code: 93, name: "Bikaner", stateName: "Rajasthan", stateShort: "RJ" },
  94: { code: 94, name: "Bundi", stateName: "Rajasthan", stateShort: "RJ" },
  95: { code: 95, name: "Chittorgarh", stateName: "Rajasthan", stateShort: "RJ" },
  96: { code: 96, name: "Churu", stateName: "Rajasthan", stateShort: "RJ" },
  97: { code: 97, name: "Dausa", stateName: "Rajasthan", stateShort: "RJ" },
  98: { code: 98, name: "Dholpur", stateName: "Rajasthan", stateShort: "RJ" },
  99: { code: 99, name: "Dungarpur", stateName: "Rajasthan", stateShort: "RJ" },
  100: { code: 100, name: "Ganganagar", stateName: "Rajasthan", stateShort: "RJ" },
  101: { code: 101, name: "Hanumangarh", stateName: "Rajasthan", stateShort: "RJ" },
  102: { code: 102, name: "Jaipur", stateName: "Rajasthan", stateShort: "RJ" },
  103: { code: 103, name: "Jaisalmer", stateName: "Rajasthan", stateShort: "RJ" },
  104: { code: 104, name: "Jalore", stateName: "Rajasthan", stateShort: "RJ" },
  105: { code: 105, name: "Jhalawar", stateName: "Rajasthan", stateShort: "RJ" },
  106: { code: 106, name: "Jhunjhunu", stateName: "Rajasthan", stateShort: "RJ" },
  107: { code: 107, name: "Jodhpur", stateName: "Rajasthan", stateShort: "RJ" },
  108: { code: 108, name: "Karauli", stateName: "Rajasthan", stateShort: "RJ" },
  109: { code: 109, name: "Kota", stateName: "Rajasthan", stateShort: "RJ" },
  110: { code: 110, name: "Nagaur", stateName: "Rajasthan", stateShort: "RJ" },
  111: { code: 111, name: "Pali", stateName: "Rajasthan", stateShort: "RJ" },
  112: { code: 112, name: "Rajsamand", stateName: "Rajasthan", stateShort: "RJ" },
  113: { code: 113, name: "Sawai Madhopur", stateName: "Rajasthan", stateShort: "RJ" },
  114: { code: 114, name: "Sikar", stateName: "Rajasthan", stateShort: "RJ" },
  115: { code: 115, name: "Sirohi", stateName: "Rajasthan", stateShort: "RJ" },
  116: { code: 116, name: "Tonk", stateName: "Rajasthan", stateShort: "RJ" },
  117: { code: 117, name: "Udaipur", stateName: "Rajasthan", stateShort: "RJ" },
  118: { code: 118, name: "Agra", stateName: "Uttar Pradesh", stateShort: "UP" },
  119: { code: 119, name: "Aligarh", stateName: "Uttar Pradesh", stateShort: "UP" },
  120: { code: 120, name: "Prayagraj", stateName: "Uttar Pradesh", stateShort: "UP" },
  121: { code: 121, name: "Ambedkar Nagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  122: { code: 122, name: "Auraiya", stateName: "Uttar Pradesh", stateShort: "UP" },
  123: { code: 123, name: "Azamgarh", stateName: "Uttar Pradesh", stateShort: "UP" },
  124: { code: 124, name: "Baghpat", stateName: "Uttar Pradesh", stateShort: "UP" },
  125: { code: 125, name: "Bahraich", stateName: "Uttar Pradesh", stateShort: "UP" },
  126: { code: 126, name: "Ballia", stateName: "Uttar Pradesh", stateShort: "UP" },
  127: { code: 127, name: "Balrampur", stateName: "Uttar Pradesh", stateShort: "UP" },
  128: { code: 128, name: "Banda", stateName: "Uttar Pradesh", stateShort: "UP" },
  129: { code: 129, name: "Bara Banki", stateName: "Uttar Pradesh", stateShort: "UP" },
  130: { code: 130, name: "Bareilly", stateName: "Uttar Pradesh", stateShort: "UP" },
  131: { code: 131, name: "Basti", stateName: "Uttar Pradesh", stateShort: "UP" },
  132: { code: 132, name: "Bijnor", stateName: "Uttar Pradesh", stateShort: "UP" },
  133: { code: 133, name: "Budaun", stateName: "Uttar Pradesh", stateShort: "UP" },
  134: { code: 134, name: "Bulandshahr", stateName: "Uttar Pradesh", stateShort: "UP" },
  135: { code: 135, name: "Chandauli", stateName: "Uttar Pradesh", stateShort: "UP" },
  136: { code: 136, name: "Chitrakoot", stateName: "Uttar Pradesh", stateShort: "UP" },
  137: { code: 137, name: "Deoria", stateName: "Uttar Pradesh", stateShort: "UP" },
  138: { code: 138, name: "Etah", stateName: "Uttar Pradesh", stateShort: "UP" },
  139: { code: 139, name: "Etawah", stateName: "Uttar Pradesh", stateShort: "UP" },
  140: { code: 140, name: "Ayodhya", stateName: "Uttar Pradesh", stateShort: "UP" },
  141: { code: 141, name: "Farrukhabad", stateName: "Uttar Pradesh", stateShort: "UP" },
  142: { code: 142, name: "Fatehpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  143: { code: 143, name: "Firozabad", stateName: "Uttar Pradesh", stateShort: "UP" },
  144: { code: 144, name: "Gautam Buddha Nagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  145: { code: 145, name: "Ghaziabad", stateName: "Uttar Pradesh", stateShort: "UP" },
  146: { code: 146, name: "Ghazipur", stateName: "Uttar Pradesh", stateShort: "UP" },
  147: { code: 147, name: "Gonda", stateName: "Uttar Pradesh", stateShort: "UP" },
  148: { code: 148, name: "Gorakhpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  149: { code: 149, name: "Hamirpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  150: { code: 150, name: "Hardoi", stateName: "Uttar Pradesh", stateShort: "UP" },
  151: { code: 151, name: "Jalaun", stateName: "Uttar Pradesh", stateShort: "UP" },
  152: { code: 152, name: "Jaunpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  153: { code: 153, name: "Jhansi", stateName: "Uttar Pradesh", stateShort: "UP" },
  154: { code: 154, name: "Amroha", stateName: "Uttar Pradesh", stateShort: "UP" },
  155: { code: 155, name: "Kannauj", stateName: "Uttar Pradesh", stateShort: "UP" },
  156: { code: 156, name: "Kanpur Dehat", stateName: "Uttar Pradesh", stateShort: "UP" },
  157: { code: 157, name: "Kanpur Nagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  158: { code: 158, name: "Kaushambi", stateName: "Uttar Pradesh", stateShort: "UP" },
  159: { code: 159, name: "Kheri", stateName: "Uttar Pradesh", stateShort: "UP" },
  160: { code: 160, name: "Kushinagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  161: { code: 161, name: "Lalitpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  162: { code: 162, name: "Lucknow", stateName: "Uttar Pradesh", stateShort: "UP" },
  163: { code: 163, name: "Hathras", stateName: "Uttar Pradesh", stateShort: "UP" },
  164: { code: 164, name: "Mahrajganj", stateName: "Uttar Pradesh", stateShort: "UP" },
  165: { code: 165, name: "Mahoba", stateName: "Uttar Pradesh", stateShort: "UP" },
  166: { code: 166, name: "Mainpuri", stateName: "Uttar Pradesh", stateShort: "UP" },
  167: { code: 167, name: "Mathura", stateName: "Uttar Pradesh", stateShort: "UP" },
  168: { code: 168, name: "Mau", stateName: "Uttar Pradesh", stateShort: "UP" },
  169: { code: 169, name: "Meerut", stateName: "Uttar Pradesh", stateShort: "UP" },
  170: { code: 170, name: "Mirzapur", stateName: "Uttar Pradesh", stateShort: "UP" },
  171: { code: 171, name: "Moradabad", stateName: "Uttar Pradesh", stateShort: "UP" },
  172: { code: 172, name: "Muzaffarnagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  173: { code: 173, name: "Pilibhit", stateName: "Uttar Pradesh", stateShort: "UP" },
  174: { code: 174, name: "Pratapgarh", stateName: "Uttar Pradesh", stateShort: "UP" },
  175: { code: 175, name: "Rae Bareli", stateName: "Uttar Pradesh", stateShort: "UP" },
  176: { code: 176, name: "Rampur", stateName: "Uttar Pradesh", stateShort: "UP" },
  177: { code: 177, name: "Saharanpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  178: { code: 178, name: "Sant Kabir Nagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  179: { code: 179, name: "Bhadohi", stateName: "Uttar Pradesh", stateShort: "UP" },
  180: { code: 180, name: "Shahjahanpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  181: { code: 181, name: "Shrawasti", stateName: "Uttar Pradesh", stateShort: "UP" },
  182: { code: 182, name: "Siddharthnagar", stateName: "Uttar Pradesh", stateShort: "UP" },
  183: { code: 183, name: "Sitapur", stateName: "Uttar Pradesh", stateShort: "UP" },
  184: { code: 184, name: "Sonbhadra", stateName: "Uttar Pradesh", stateShort: "UP" },
  185: { code: 185, name: "Sultanpur", stateName: "Uttar Pradesh", stateShort: "UP" },
  186: { code: 186, name: "Unnao", stateName: "Uttar Pradesh", stateShort: "UP" },
  187: { code: 187, name: "Varanasi", stateName: "Uttar Pradesh", stateShort: "UP" },
  188: { code: 188, name: "Araria", stateName: "Bihar", stateShort: "BR" },
  189: { code: 189, name: "Aurangabad", stateName: "Bihar", stateShort: "BR" },
  190: { code: 190, name: "Banka", stateName: "Bihar", stateShort: "BR" },
  191: { code: 191, name: "Begusarai", stateName: "Bihar", stateShort: "BR" },
  192: { code: 192, name: "Bhagalpur", stateName: "Bihar", stateShort: "BR" },
  193: { code: 193, name: "Bhojpur", stateName: "Bihar", stateShort: "BR" },
  194: { code: 194, name: "Buxar", stateName: "Bihar", stateShort: "BR" },
  195: { code: 195, name: "Darbhanga", stateName: "Bihar", stateShort: "BR" },
  196: { code: 196, name: "Gaya", stateName: "Bihar", stateShort: "BR" },
  197: { code: 197, name: "Gopalganj", stateName: "Bihar", stateShort: "BR" },
  198: { code: 198, name: "Jamui", stateName: "Bihar", stateShort: "BR" },
  199: { code: 199, name: "Jehanabad", stateName: "Bihar", stateShort: "BR" },
  200: { code: 200, name: "Kaimur (Bhabua)", stateName: "Bihar", stateShort: "BR" },
  201: { code: 201, name: "Katihar", stateName: "Bihar", stateShort: "BR" },
  202: { code: 202, name: "Khagaria", stateName: "Bihar", stateShort: "BR" },
  203: { code: 203, name: "Kishanganj", stateName: "Bihar", stateShort: "BR" },
  204: { code: 204, name: "Lakhisarai", stateName: "Bihar", stateShort: "BR" },
  205: { code: 205, name: "Madhepura", stateName: "Bihar", stateShort: "BR" },
  206: { code: 206, name: "Madhubani", stateName: "Bihar", stateShort: "BR" },
  207: { code: 207, name: "Munger", stateName: "Bihar", stateShort: "BR" },
  208: { code: 208, name: "Muzaffarpur", stateName: "Bihar", stateShort: "BR" },
  209: { code: 209, name: "Nalanda", stateName: "Bihar", stateShort: "BR" },
  210: { code: 210, name: "Nawada", stateName: "Bihar", stateShort: "BR" },
  211: { code: 211, name: "Pashchim Champaran", stateName: "Bihar", stateShort: "BR" },
  212: { code: 212, name: "Patna", stateName: "Bihar", stateShort: "BR" },
  213: { code: 213, name: "Purbi Champaran", stateName: "Bihar", stateShort: "BR" },
  214: { code: 214, name: "Purnia", stateName: "Bihar", stateShort: "BR" },
  215: { code: 215, name: "Rohtas", stateName: "Bihar", stateShort: "BR" },
  216: { code: 216, name: "Saharsa", stateName: "Bihar", stateShort: "BR" },
  217: { code: 217, name: "Samastipur", stateName: "Bihar", stateShort: "BR" },
  218: { code: 218, name: "Saran", stateName: "Bihar", stateShort: "BR" },
  219: { code: 219, name: "Sheikhpura", stateName: "Bihar", stateShort: "BR" },
  220: { code: 220, name: "Sheohar", stateName: "Bihar", stateShort: "BR" },
  221: { code: 221, name: "Sitamarhi", stateName: "Bihar", stateShort: "BR" },
  222: { code: 222, name: "Siwan", stateName: "Bihar", stateShort: "BR" },
  223: { code: 223, name: "Supaul", stateName: "Bihar", stateShort: "BR" },
  224: { code: 224, name: "Vaishali", stateName: "Bihar", stateShort: "BR" },
  225: { code: 225, name: "Gangtok", stateName: "Sikkim", stateShort: "SK" },
  226: { code: 226, name: "Mangan", stateName: "Sikkim", stateShort: "SK" },
  227: { code: 227, name: "Namchi", stateName: "Sikkim", stateShort: "SK" },
  228: { code: 228, name: "Gyalshing", stateName: "Sikkim", stateShort: "SK" },
  229: { code: 229, name: "Changlang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  230: { code: 230, name: "Dibang Valley", stateName: "Arunachal Pradesh", stateShort: "AR" },
  231: { code: 231, name: "East Kameng", stateName: "Arunachal Pradesh", stateShort: "AR" },
  232: { code: 232, name: "East Siang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  233: { code: 233, name: "Kurung Kumey", stateName: "Arunachal Pradesh", stateShort: "AR" },
  234: { code: 234, name: "Lohit", stateName: "Arunachal Pradesh", stateShort: "AR" },
  235: { code: 235, name: "Lower Dibang Valley", stateName: "Arunachal Pradesh", stateShort: "AR" },
  236: { code: 236, name: "Lower Subansiri", stateName: "Arunachal Pradesh", stateShort: "AR" },
  237: { code: 237, name: "Papum Pare", stateName: "Arunachal Pradesh", stateShort: "AR" },
  238: { code: 238, name: "Tawang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  239: { code: 239, name: "Tirap", stateName: "Arunachal Pradesh", stateShort: "AR" },
  240: { code: 240, name: "Upper Siang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  241: { code: 241, name: "Upper Subansiri", stateName: "Arunachal Pradesh", stateShort: "AR" },
  242: { code: 242, name: "West Kameng", stateName: "Arunachal Pradesh", stateShort: "AR" },
  243: { code: 243, name: "West Siang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  244: { code: 244, name: "Dimapur", stateName: "Nagaland", stateShort: "NL" },
  245: { code: 245, name: "Kohima", stateName: "Nagaland", stateShort: "NL" },
  246: { code: 246, name: "Mokokchung", stateName: "Nagaland", stateShort: "NL" },
  247: { code: 247, name: "Mon", stateName: "Nagaland", stateShort: "NL" },
  248: { code: 248, name: "Phek", stateName: "Nagaland", stateShort: "NL" },
  249: { code: 249, name: "Tuensang", stateName: "Nagaland", stateShort: "NL" },
  250: { code: 250, name: "Wokha", stateName: "Nagaland", stateShort: "NL" },
  251: { code: 251, name: "Zunheboto", stateName: "Nagaland", stateShort: "NL" },
  252: { code: 252, name: "Bishnupur", stateName: "Manipur", stateShort: "MN" },
  253: { code: 253, name: "Chandel", stateName: "Manipur", stateShort: "MN" },
  254: { code: 254, name: "Churachandpur", stateName: "Manipur", stateShort: "MN" },
  255: { code: 255, name: "Imphal East", stateName: "Manipur", stateShort: "MN" },
  256: { code: 256, name: "Imphal West", stateName: "Manipur", stateShort: "MN" },
  257: { code: 257, name: "Senapati", stateName: "Manipur", stateShort: "MN" },
  258: { code: 258, name: "Tamenglong", stateName: "Manipur", stateShort: "MN" },
  259: { code: 259, name: "Thoubal", stateName: "Manipur", stateShort: "MN" },
  260: { code: 260, name: "Ukhrul", stateName: "Manipur", stateShort: "MN" },
  261: { code: 261, name: "Aizawl", stateName: "Mizoram", stateShort: "MZ" },
  262: { code: 262, name: "Champhai", stateName: "Mizoram", stateShort: "MZ" },
  263: { code: 263, name: "Kolasib", stateName: "Mizoram", stateShort: "MZ" },
  264: { code: 264, name: "Lawngtlai", stateName: "Mizoram", stateShort: "MZ" },
  265: { code: 265, name: "Lunglei", stateName: "Mizoram", stateShort: "MZ" },
  266: { code: 266, name: "Mamit", stateName: "Mizoram", stateShort: "MZ" },
  267: { code: 267, name: "Siaha", stateName: "Mizoram", stateShort: "MZ" },
  268: { code: 268, name: "Serchhip", stateName: "Mizoram", stateShort: "MZ" },
  269: { code: 269, name: "Dhalai", stateName: "Tripura", stateShort: "TR" },
  270: { code: 270, name: "North Tripura", stateName: "Tripura", stateShort: "TR" },
  271: { code: 271, name: "South Tripura", stateName: "Tripura", stateShort: "TR" },
  272: { code: 272, name: "West Tripura", stateName: "Tripura", stateShort: "TR" },
  273: { code: 273, name: "East Garo Hills", stateName: "Meghalaya", stateShort: "ML" },
  274: { code: 274, name: "East Khasi Hills", stateName: "Meghalaya", stateShort: "ML" },
  275: { code: 275, name: "West Jaintia Hills", stateName: "Meghalaya", stateShort: "ML" },
  276: { code: 276, name: "Ri Bhoi", stateName: "Meghalaya", stateShort: "ML" },
  277: { code: 277, name: "South Garo Hills", stateName: "Meghalaya", stateShort: "ML" },
  278: { code: 278, name: "West Garo Hills", stateName: "Meghalaya", stateShort: "ML" },
  279: { code: 279, name: "West Khasi Hills", stateName: "Meghalaya", stateShort: "ML" },
  280: { code: 280, name: "Barpeta", stateName: "Assam", stateShort: "AS" },
  281: { code: 281, name: "Bongaigaon", stateName: "Assam", stateShort: "AS" },
  282: { code: 282, name: "Cachar", stateName: "Assam", stateShort: "AS" },
  283: { code: 283, name: "Darrang", stateName: "Assam", stateShort: "AS" },
  284: { code: 284, name: "Dhemaji", stateName: "Assam", stateShort: "AS" },
  285: { code: 285, name: "Dhubri", stateName: "Assam", stateShort: "AS" },
  286: { code: 286, name: "Dibrugarh", stateName: "Assam", stateShort: "AS" },
  287: { code: 287, name: "Goalpara", stateName: "Assam", stateShort: "AS" },
  288: { code: 288, name: "Golaghat", stateName: "Assam", stateShort: "AS" },
  289: { code: 289, name: "Hailakandi", stateName: "Assam", stateShort: "AS" },
  290: { code: 290, name: "Jorhat", stateName: "Assam", stateShort: "AS" },
  291: { code: 291, name: "Kamrup", stateName: "Assam", stateShort: "AS" },
  292: { code: 292, name: "Karbi Anglong", stateName: "Assam", stateShort: "AS" },
  293: { code: 293, name: "Sribhumi", stateName: "Assam", stateShort: "AS" },
  294: { code: 294, name: "Kokrajhar", stateName: "Assam", stateShort: "AS" },
  295: { code: 295, name: "Lakhimpur", stateName: "Assam", stateShort: "AS" },
  296: { code: 296, name: "Marigaon", stateName: "Assam", stateShort: "AS" },
  297: { code: 297, name: "Nagaon", stateName: "Assam", stateShort: "AS" },
  298: { code: 298, name: "Nalbari", stateName: "Assam", stateShort: "AS" },
  299: { code: 299, name: "Dima Hasao", stateName: "Assam", stateShort: "AS" },
  300: { code: 300, name: "Sivasagar", stateName: "Assam", stateShort: "AS" },
  301: { code: 301, name: "Sonitpur", stateName: "Assam", stateShort: "AS" },
  302: { code: 302, name: "Tinsukia", stateName: "Assam", stateShort: "AS" },
  303: { code: 303, name: "North 24 Parganas", stateName: "West Bengal", stateShort: "WB" },
  304: { code: 304, name: "South 24 Parganas", stateName: "West Bengal", stateShort: "WB" },
  305: { code: 305, name: "Bankura", stateName: "West Bengal", stateShort: "WB" },
  306: { code: 306, name: "Purba Bardhaman", stateName: "West Bengal", stateShort: "WB" },
  307: { code: 307, name: "Birbhum", stateName: "West Bengal", stateShort: "WB" },
  308: { code: 308, name: "Cooch Behar", stateName: "West Bengal", stateShort: "WB" },
  309: { code: 309, name: "Darjeeling", stateName: "West Bengal", stateShort: "WB" },
  310: { code: 310, name: "Dakshin Dinajpur", stateName: "West Bengal", stateShort: "WB" },
  311: { code: 311, name: "Uttar Dinajpur", stateName: "West Bengal", stateShort: "WB" },
  312: { code: 312, name: "Hooghly", stateName: "West Bengal", stateShort: "WB" },
  313: { code: 313, name: "Howrah", stateName: "West Bengal", stateShort: "WB" },
  314: { code: 314, name: "Jalpaiguri", stateName: "West Bengal", stateShort: "WB" },
  315: { code: 315, name: "Kolkata", stateName: "West Bengal", stateShort: "WB" },
  316: { code: 316, name: "Malda", stateName: "West Bengal", stateShort: "WB" },
  317: { code: 317, name: "Purba Medinipur", stateName: "West Bengal", stateShort: "WB" },
  318: { code: 318, name: "Paschim Medinipur", stateName: "West Bengal", stateShort: "WB" },
  319: { code: 319, name: "Murshidabad", stateName: "West Bengal", stateShort: "WB" },
  320: { code: 320, name: "Nadia", stateName: "West Bengal", stateShort: "WB" },
  321: { code: 321, name: "Purulia", stateName: "West Bengal", stateShort: "WB" },
  322: { code: 322, name: "Bokaro", stateName: "Jharkhand", stateShort: "JH" },
  323: { code: 323, name: "Chatra", stateName: "Jharkhand", stateShort: "JH" },
  324: { code: 324, name: "Deoghar", stateName: "Jharkhand", stateShort: "JH" },
  325: { code: 325, name: "Dhanbad", stateName: "Jharkhand", stateShort: "JH" },
  326: { code: 326, name: "Dumka", stateName: "Jharkhand", stateShort: "JH" },
  327: { code: 327, name: "East Singhbum", stateName: "Jharkhand", stateShort: "JH" },
  328: { code: 328, name: "Garhwa", stateName: "Jharkhand", stateShort: "JH" },
  329: { code: 329, name: "Giridih", stateName: "Jharkhand", stateShort: "JH" },
  330: { code: 330, name: "Godda", stateName: "Jharkhand", stateShort: "JH" },
  331: { code: 331, name: "Gumla", stateName: "Jharkhand", stateShort: "JH" },
  332: { code: 332, name: "Hazaribagh", stateName: "Jharkhand", stateShort: "JH" },
  333: { code: 333, name: "Jamtara", stateName: "Jharkhand", stateShort: "JH" },
  334: { code: 334, name: "Koderma", stateName: "Jharkhand", stateShort: "JH" },
  335: { code: 335, name: "Latehar", stateName: "Jharkhand", stateShort: "JH" },
  336: { code: 336, name: "Lohardaga", stateName: "Jharkhand", stateShort: "JH" },
  337: { code: 337, name: "Pakur", stateName: "Jharkhand", stateShort: "JH" },
  338: { code: 338, name: "Palamu", stateName: "Jharkhand", stateShort: "JH" },
  339: { code: 339, name: "Ranchi", stateName: "Jharkhand", stateShort: "JH" },
  340: { code: 340, name: "Sahebganj", stateName: "Jharkhand", stateShort: "JH" },
  341: { code: 341, name: "Saraikela Kharsawan", stateName: "Jharkhand", stateShort: "JH" },
  342: { code: 342, name: "Simdega", stateName: "Jharkhand", stateShort: "JH" },
  343: { code: 343, name: "West Singhbhum", stateName: "Jharkhand", stateShort: "JH" },
  344: { code: 344, name: "Anugola", stateName: "Odisha", stateShort: "OD" },
  345: { code: 345, name: "Balangir", stateName: "Odisha", stateShort: "OD" },
  346: { code: 346, name: "Baleshwar", stateName: "Odisha", stateShort: "OD" },
  347: { code: 347, name: "Baragada", stateName: "Odisha", stateShort: "OD" },
  348: { code: 348, name: "Bhadrak", stateName: "Odisha", stateShort: "OD" },
  349: { code: 349, name: "Boudh", stateName: "Odisha", stateShort: "OD" },
  350: { code: 350, name: "Kataka", stateName: "Odisha", stateShort: "OD" },
  351: { code: 351, name: "Debagada", stateName: "Odisha", stateShort: "OD" },
  352: { code: 352, name: "Dhenkanal", stateName: "Odisha", stateShort: "OD" },
  353: { code: 353, name: "Gajapati", stateName: "Odisha", stateShort: "OD" },
  354: { code: 354, name: "Ganjam", stateName: "Odisha", stateShort: "OD" },
  355: { code: 355, name: "Jagatsinghapur", stateName: "Odisha", stateShort: "OD" },
  356: { code: 356, name: "Jajpur", stateName: "Odisha", stateShort: "OD" },
  357: { code: 357, name: "Jharsuguda", stateName: "Odisha", stateShort: "OD" },
  358: { code: 358, name: "Kalahandi", stateName: "Odisha", stateShort: "OD" },
  359: { code: 359, name: "Kandhamala", stateName: "Odisha", stateShort: "OD" },
  360: { code: 360, name: "Kendrapada", stateName: "Odisha", stateShort: "OD" },
  361: { code: 361, name: "Kendujhar", stateName: "Odisha", stateShort: "OD" },
  362: { code: 362, name: "Khordha", stateName: "Odisha", stateShort: "OD" },
  363: { code: 363, name: "Koraput", stateName: "Odisha", stateShort: "OD" },
  364: { code: 364, name: "Malkangiri", stateName: "Odisha", stateShort: "OD" },
  365: { code: 365, name: "Mayurbhanj", stateName: "Odisha", stateShort: "OD" },
  366: { code: 366, name: "Nabarangpur", stateName: "Odisha", stateShort: "OD" },
  367: { code: 367, name: "Nayagada", stateName: "Odisha", stateShort: "OD" },
  368: { code: 368, name: "Nuapada", stateName: "Odisha", stateShort: "OD" },
  369: { code: 369, name: "Puri", stateName: "Odisha", stateShort: "OD" },
  370: { code: 370, name: "Rayagada", stateName: "Odisha", stateShort: "OD" },
  371: { code: 371, name: "Sambalpur", stateName: "Odisha", stateShort: "OD" },
  372: { code: 372, name: "Subarnapur", stateName: "Odisha", stateShort: "OD" },
  373: { code: 373, name: "Sundaragada", stateName: "Odisha", stateShort: "OD" },
  374: { code: 374, name: "Bastar", stateName: "Chhattisgarh", stateShort: "CG" },
  375: { code: 375, name: "Bilaspur", stateName: "Chhattisgarh", stateShort: "CG" },
  376: { code: 376, name: "Dakshin Bastar Dantewada", stateName: "Chhattisgarh", stateShort: "CG" },
  377: { code: 377, name: "Dhamtari", stateName: "Chhattisgarh", stateShort: "CG" },
  378: { code: 378, name: "Durg", stateName: "Chhattisgarh", stateShort: "CG" },
  379: { code: 379, name: "Janjgir-Champa", stateName: "Chhattisgarh", stateShort: "CG" },
  380: { code: 380, name: "Jashpur", stateName: "Chhattisgarh", stateShort: "CG" },
  381: { code: 381, name: "Uttar Bastar Kanker", stateName: "Chhattisgarh", stateShort: "CG" },
  382: { code: 382, name: "Kabeerdham", stateName: "Chhattisgarh", stateShort: "CG" },
  383: { code: 383, name: "Korba", stateName: "Chhattisgarh", stateShort: "CG" },
  384: { code: 384, name: "Korea", stateName: "Chhattisgarh", stateShort: "CG" },
  385: { code: 385, name: "Mahasamund", stateName: "Chhattisgarh", stateShort: "CG" },
  386: { code: 386, name: "Raigarh", stateName: "Chhattisgarh", stateShort: "CG" },
  387: { code: 387, name: "Raipur", stateName: "Chhattisgarh", stateShort: "CG" },
  388: { code: 388, name: "Rajnandgaon", stateName: "Chhattisgarh", stateShort: "CG" },
  389: { code: 389, name: "Surguja", stateName: "Chhattisgarh", stateShort: "CG" },
  390: { code: 390, name: "Anuppur", stateName: "Madhya Pradesh", stateShort: "MP" },
  391: { code: 391, name: "Ashoknagar", stateName: "Madhya Pradesh", stateShort: "MP" },
  392: { code: 392, name: "Balaghat", stateName: "Madhya Pradesh", stateShort: "MP" },
  393: { code: 393, name: "Barwani", stateName: "Madhya Pradesh", stateShort: "MP" },
  394: { code: 394, name: "Betul", stateName: "Madhya Pradesh", stateShort: "MP" },
  395: { code: 395, name: "Bhind", stateName: "Madhya Pradesh", stateShort: "MP" },
  396: { code: 396, name: "Bhopal", stateName: "Madhya Pradesh", stateShort: "MP" },
  397: { code: 397, name: "Burhanpur", stateName: "Madhya Pradesh", stateShort: "MP" },
  398: { code: 398, name: "Chhatarpur", stateName: "Madhya Pradesh", stateShort: "MP" },
  399: { code: 399, name: "Chhindwara", stateName: "Madhya Pradesh", stateShort: "MP" },
  400: { code: 400, name: "Damoh", stateName: "Madhya Pradesh", stateShort: "MP" },
  401: { code: 401, name: "Datia", stateName: "Madhya Pradesh", stateShort: "MP" },
  402: { code: 402, name: "Dewas", stateName: "Madhya Pradesh", stateShort: "MP" },
  403: { code: 403, name: "Dhar", stateName: "Madhya Pradesh", stateShort: "MP" },
  404: { code: 404, name: "Dindori", stateName: "Madhya Pradesh", stateShort: "MP" },
  405: { code: 405, name: "Khandwa (East Nimar)", stateName: "Madhya Pradesh", stateShort: "MP" },
  406: { code: 406, name: "Guna", stateName: "Madhya Pradesh", stateShort: "MP" },
  407: { code: 407, name: "Gwalior", stateName: "Madhya Pradesh", stateShort: "MP" },
  408: { code: 408, name: "Harda", stateName: "Madhya Pradesh", stateShort: "MP" },
  409: { code: 409, name: "Narmadapuram", stateName: "Madhya Pradesh", stateShort: "MP" },
  410: { code: 410, name: "Indore", stateName: "Madhya Pradesh", stateShort: "MP" },
  411: { code: 411, name: "Jabalpur", stateName: "Madhya Pradesh", stateShort: "MP" },
  412: { code: 412, name: "Jhabua", stateName: "Madhya Pradesh", stateShort: "MP" },
  413: { code: 413, name: "Katni", stateName: "Madhya Pradesh", stateShort: "MP" },
  414: { code: 414, name: "Khargone (West Nimar)", stateName: "Madhya Pradesh", stateShort: "MP" },
  415: { code: 415, name: "Mandla", stateName: "Madhya Pradesh", stateShort: "MP" },
  416: { code: 416, name: "Mandsaur", stateName: "Madhya Pradesh", stateShort: "MP" },
  417: { code: 417, name: "Morena", stateName: "Madhya Pradesh", stateShort: "MP" },
  418: { code: 418, name: "Narsimhapur", stateName: "Madhya Pradesh", stateShort: "MP" },
  419: { code: 419, name: "Neemuch", stateName: "Madhya Pradesh", stateShort: "MP" },
  420: { code: 420, name: "Panna", stateName: "Madhya Pradesh", stateShort: "MP" },
  421: { code: 421, name: "Raisen", stateName: "Madhya Pradesh", stateShort: "MP" },
  422: { code: 422, name: "Rajgarh", stateName: "Madhya Pradesh", stateShort: "MP" },
  423: { code: 423, name: "Ratlam", stateName: "Madhya Pradesh", stateShort: "MP" },
  424: { code: 424, name: "Rewa", stateName: "Madhya Pradesh", stateShort: "MP" },
  425: { code: 425, name: "Sagar", stateName: "Madhya Pradesh", stateShort: "MP" },
  426: { code: 426, name: "Satna", stateName: "Madhya Pradesh", stateShort: "MP" },
  427: { code: 427, name: "Sehore", stateName: "Madhya Pradesh", stateShort: "MP" },
  428: { code: 428, name: "Seoni", stateName: "Madhya Pradesh", stateShort: "MP" },
  429: { code: 429, name: "Shahdol", stateName: "Madhya Pradesh", stateShort: "MP" },
  430: { code: 430, name: "Shajapur", stateName: "Madhya Pradesh", stateShort: "MP" },
  431: { code: 431, name: "Sheopur", stateName: "Madhya Pradesh", stateShort: "MP" },
  432: { code: 432, name: "Shivpuri", stateName: "Madhya Pradesh", stateShort: "MP" },
  433: { code: 433, name: "Sidhi", stateName: "Madhya Pradesh", stateShort: "MP" },
  434: { code: 434, name: "Tikamgarh", stateName: "Madhya Pradesh", stateShort: "MP" },
  435: { code: 435, name: "Ujjain", stateName: "Madhya Pradesh", stateShort: "MP" },
  436: { code: 436, name: "Umaria", stateName: "Madhya Pradesh", stateShort: "MP" },
  437: { code: 437, name: "Vidisha", stateName: "Madhya Pradesh", stateShort: "MP" },
  438: { code: 438, name: "Ahmedabad", stateName: "Gujarat", stateShort: "GJ" },
  439: { code: 439, name: "Amreli", stateName: "Gujarat", stateShort: "GJ" },
  440: { code: 440, name: "Anand", stateName: "Gujarat", stateShort: "GJ" },
  441: { code: 441, name: "Banas Kantha", stateName: "Gujarat", stateShort: "GJ" },
  442: { code: 442, name: "Bharuch", stateName: "Gujarat", stateShort: "GJ" },
  443: { code: 443, name: "Bhavnagar", stateName: "Gujarat", stateShort: "GJ" },
  444: { code: 444, name: "Dangs", stateName: "Gujarat", stateShort: "GJ" },
  445: { code: 445, name: "Dahod", stateName: "Gujarat", stateShort: "GJ" },
  446: { code: 446, name: "Gandhinagar", stateName: "Gujarat", stateShort: "GJ" },
  447: { code: 447, name: "Jamnagar", stateName: "Gujarat", stateShort: "GJ" },
  448: { code: 448, name: "Junagadh", stateName: "Gujarat", stateShort: "GJ" },
  449: { code: 449, name: "Kachchh", stateName: "Gujarat", stateShort: "GJ" },
  450: { code: 450, name: "Kheda", stateName: "Gujarat", stateShort: "GJ" },
  451: { code: 451, name: "Mahesana", stateName: "Gujarat", stateShort: "GJ" },
  452: { code: 452, name: "Narmada", stateName: "Gujarat", stateShort: "GJ" },
  453: { code: 453, name: "Navsari", stateName: "Gujarat", stateShort: "GJ" },
  454: { code: 454, name: "Panch Mahals", stateName: "Gujarat", stateShort: "GJ" },
  455: { code: 455, name: "Patan", stateName: "Gujarat", stateShort: "GJ" },
  456: { code: 456, name: "Porbandar", stateName: "Gujarat", stateShort: "GJ" },
  457: { code: 457, name: "Rajkot", stateName: "Gujarat", stateShort: "GJ" },
  458: { code: 458, name: "Sabar Kantha", stateName: "Gujarat", stateShort: "GJ" },
  459: { code: 459, name: "Surat", stateName: "Gujarat", stateShort: "GJ" },
  460: { code: 460, name: "Surendranagar", stateName: "Gujarat", stateShort: "GJ" },
  461: { code: 461, name: "Vadodara", stateName: "Gujarat", stateShort: "GJ" },
  462: { code: 462, name: "Valsad", stateName: "Gujarat", stateShort: "GJ" },
  463: { code: 463, name: "Daman", stateName: "The Dadra And Nagar Haveli And Daman And Diu", stateShort: "DD" },
  464: { code: 464, name: "Diu", stateName: "The Dadra And Nagar Haveli And Daman And Diu", stateShort: "DD" },
  465: { code: 465, name: "Dadra And Nagar Haveli", stateName: "The Dadra And Nagar Haveli And Daman And Diu", stateShort: "DD" },
  466: { code: 466, name: "Ahilyanagar", stateName: "Maharashtra", stateShort: "MH" },
  467: { code: 467, name: "Akola", stateName: "Maharashtra", stateShort: "MH" },
  468: { code: 468, name: "Amravati", stateName: "Maharashtra", stateShort: "MH" },
  469: { code: 469, name: "Chhatrapati Sambhajinagar", stateName: "Maharashtra", stateShort: "MH" },
  470: { code: 470, name: "Beed", stateName: "Maharashtra", stateShort: "MH" },
  471: { code: 471, name: "Bhandara", stateName: "Maharashtra", stateShort: "MH" },
  472: { code: 472, name: "Buldhana", stateName: "Maharashtra", stateShort: "MH" },
  473: { code: 473, name: "Chandrapur", stateName: "Maharashtra", stateShort: "MH" },
  474: { code: 474, name: "Dhule", stateName: "Maharashtra", stateShort: "MH" },
  475: { code: 475, name: "Gadchiroli", stateName: "Maharashtra", stateShort: "MH" },
  476: { code: 476, name: "Gondia", stateName: "Maharashtra", stateShort: "MH" },
  477: { code: 477, name: "Hingoli", stateName: "Maharashtra", stateShort: "MH" },
  478: { code: 478, name: "Jalgaon", stateName: "Maharashtra", stateShort: "MH" },
  479: { code: 479, name: "Jalna", stateName: "Maharashtra", stateShort: "MH" },
  480: { code: 480, name: "Kolhapur", stateName: "Maharashtra", stateShort: "MH" },
  481: { code: 481, name: "Latur", stateName: "Maharashtra", stateShort: "MH" },
  482: { code: 482, name: "Mumbai", stateName: "Maharashtra", stateShort: "MH" },
  483: { code: 483, name: "Mumbai Suburban", stateName: "Maharashtra", stateShort: "MH" },
  484: { code: 484, name: "Nagpur", stateName: "Maharashtra", stateShort: "MH" },
  485: { code: 485, name: "Nanded", stateName: "Maharashtra", stateShort: "MH" },
  486: { code: 486, name: "Nandurbar", stateName: "Maharashtra", stateShort: "MH" },
  487: { code: 487, name: "Nashik", stateName: "Maharashtra", stateShort: "MH" },
  488: { code: 488, name: "Dharashiv", stateName: "Maharashtra", stateShort: "MH" },
  489: { code: 489, name: "Parbhani", stateName: "Maharashtra", stateShort: "MH" },
  490: { code: 490, name: "Pune", stateName: "Maharashtra", stateShort: "MH" },
  491: { code: 491, name: "Raigad", stateName: "Maharashtra", stateShort: "MH" },
  492: { code: 492, name: "Ratnagiri", stateName: "Maharashtra", stateShort: "MH" },
  493: { code: 493, name: "Sangli", stateName: "Maharashtra", stateShort: "MH" },
  494: { code: 494, name: "Satara", stateName: "Maharashtra", stateShort: "MH" },
  495: { code: 495, name: "Sindhudurg", stateName: "Maharashtra", stateShort: "MH" },
  496: { code: 496, name: "Solapur", stateName: "Maharashtra", stateShort: "MH" },
  497: { code: 497, name: "Thane", stateName: "Maharashtra", stateShort: "MH" },
  498: { code: 498, name: "Wardha", stateName: "Maharashtra", stateShort: "MH" },
  499: { code: 499, name: "Washim", stateName: "Maharashtra", stateShort: "MH" },
  500: { code: 500, name: "Yavatmal", stateName: "Maharashtra", stateShort: "MH" },
  501: { code: 501, name: "Adilabad", stateName: "Telangana", stateShort: "TS" },
  502: { code: 502, name: "Ananthapuramu", stateName: "Andhra Pradesh", stateShort: "AP" },
  503: { code: 503, name: "Chittoor", stateName: "Andhra Pradesh", stateShort: "AP" },
  504: { code: 504, name: "Y.S.R. Kadapa", stateName: "Andhra Pradesh", stateShort: "AP" },
  505: { code: 505, name: "East Godavari", stateName: "Andhra Pradesh", stateShort: "AP" },
  506: { code: 506, name: "Guntur", stateName: "Andhra Pradesh", stateShort: "AP" },
  507: { code: 507, name: "Hyderabad", stateName: "Telangana", stateShort: "TS" },
  508: { code: 508, name: "Karimnagar", stateName: "Telangana", stateShort: "TS" },
  509: { code: 509, name: "Khammam", stateName: "Telangana", stateShort: "TS" },
  510: { code: 510, name: "Krishna", stateName: "Andhra Pradesh", stateShort: "AP" },
  511: { code: 511, name: "Kurnool", stateName: "Andhra Pradesh", stateShort: "AP" },
  512: { code: 512, name: "Mahabubnagar", stateName: "Telangana", stateShort: "TS" },
  513: { code: 513, name: "Medak", stateName: "Telangana", stateShort: "TS" },
  514: { code: 514, name: "Nalgonda", stateName: "Telangana", stateShort: "TS" },
  515: { code: 515, name: "Sri Potti Sriramulu Nellore", stateName: "Andhra Pradesh", stateShort: "AP" },
  516: { code: 516, name: "Nizamabad", stateName: "Telangana", stateShort: "TS" },
  517: { code: 517, name: "Prakasam", stateName: "Andhra Pradesh", stateShort: "AP" },
  518: { code: 518, name: "Ranga Reddy", stateName: "Telangana", stateShort: "TS" },
  519: { code: 519, name: "Srikakulam", stateName: "Andhra Pradesh", stateShort: "AP" },
  520: { code: 520, name: "Visakhapatnam", stateName: "Andhra Pradesh", stateShort: "AP" },
  521: { code: 521, name: "Vizianagaram", stateName: "Andhra Pradesh", stateShort: "AP" },
  522: { code: 522, name: "Warangal", stateName: "Telangana", stateShort: "TS" },
  523: { code: 523, name: "West Godavari", stateName: "Andhra Pradesh", stateShort: "AP" },
  524: { code: 524, name: "Bagalkote", stateName: "Karnataka", stateShort: "KA" },
  525: { code: 525, name: "Bengaluru Urban", stateName: "Karnataka", stateShort: "KA" },
  526: { code: 526, name: "Bengaluru Rural", stateName: "Karnataka", stateShort: "KA" },
  527: { code: 527, name: "Belagavi", stateName: "Karnataka", stateShort: "KA" },
  528: { code: 528, name: "Ballari", stateName: "Karnataka", stateShort: "KA" },
  529: { code: 529, name: "Bidar", stateName: "Karnataka", stateShort: "KA" },
  530: { code: 530, name: "Vijayapura", stateName: "Karnataka", stateShort: "KA" },
  531: { code: 531, name: "Chamarajanagar", stateName: "Karnataka", stateShort: "KA" },
  532: { code: 532, name: "Chikkamagaluru", stateName: "Karnataka", stateShort: "KA" },
  533: { code: 533, name: "Chitradurga", stateName: "Karnataka", stateShort: "KA" },
  534: { code: 534, name: "Dakshina Kannada", stateName: "Karnataka", stateShort: "KA" },
  535: { code: 535, name: "Davanagere", stateName: "Karnataka", stateShort: "KA" },
  536: { code: 536, name: "Dharwad", stateName: "Karnataka", stateShort: "KA" },
  537: { code: 537, name: "Gadag", stateName: "Karnataka", stateShort: "KA" },
  538: { code: 538, name: "Kalaburagi", stateName: "Karnataka", stateShort: "KA" },
  539: { code: 539, name: "Hassan", stateName: "Karnataka", stateShort: "KA" },
  540: { code: 540, name: "Haveri", stateName: "Karnataka", stateShort: "KA" },
  541: { code: 541, name: "Kodagu", stateName: "Karnataka", stateShort: "KA" },
  542: { code: 542, name: "Kolar", stateName: "Karnataka", stateShort: "KA" },
  543: { code: 543, name: "Koppal", stateName: "Karnataka", stateShort: "KA" },
  544: { code: 544, name: "Mandya", stateName: "Karnataka", stateShort: "KA" },
  545: { code: 545, name: "Mysuru", stateName: "Karnataka", stateShort: "KA" },
  546: { code: 546, name: "Raichur", stateName: "Karnataka", stateShort: "KA" },
  547: { code: 547, name: "Shivamogga", stateName: "Karnataka", stateShort: "KA" },
  548: { code: 548, name: "Tumakuru", stateName: "Karnataka", stateShort: "KA" },
  549: { code: 549, name: "Udupi", stateName: "Karnataka", stateShort: "KA" },
  550: { code: 550, name: "Uttara Kannada", stateName: "Karnataka", stateShort: "KA" },
  551: { code: 551, name: "North Goa", stateName: "Goa", stateShort: "GA" },
  552: { code: 552, name: "South Goa", stateName: "Goa", stateShort: "GA" },
  553: { code: 553, name: "Lakshadweep District", stateName: "Lakshadweep", stateShort: "LD" },
  554: { code: 554, name: "Alappuzha", stateName: "Kerala", stateShort: "KL" },
  555: { code: 555, name: "Ernakulam", stateName: "Kerala", stateShort: "KL" },
  556: { code: 556, name: "Idukki", stateName: "Kerala", stateShort: "KL" },
  557: { code: 557, name: "Kannur", stateName: "Kerala", stateShort: "KL" },
  558: { code: 558, name: "Kasaragod", stateName: "Kerala", stateShort: "KL" },
  559: { code: 559, name: "Kollam", stateName: "Kerala", stateShort: "KL" },
  560: { code: 560, name: "Kottayam", stateName: "Kerala", stateShort: "KL" },
  561: { code: 561, name: "Kozhikode", stateName: "Kerala", stateShort: "KL" },
  562: { code: 562, name: "Malappuram", stateName: "Kerala", stateShort: "KL" },
  563: { code: 563, name: "Palakkad", stateName: "Kerala", stateShort: "KL" },
  564: { code: 564, name: "Pathanamthitta", stateName: "Kerala", stateShort: "KL" },
  565: { code: 565, name: "Thiruvananthapuram", stateName: "Kerala", stateShort: "KL" },
  566: { code: 566, name: "Thrissur", stateName: "Kerala", stateShort: "KL" },
  567: { code: 567, name: "Wayanad", stateName: "Kerala", stateShort: "KL" },
  568: { code: 568, name: "Chennai", stateName: "Tamil Nadu", stateShort: "TN" },
  569: { code: 569, name: "Coimbatore", stateName: "Tamil Nadu", stateShort: "TN" },
  570: { code: 570, name: "Cuddalore", stateName: "Tamil Nadu", stateShort: "TN" },
  571: { code: 571, name: "Dharmapuri", stateName: "Tamil Nadu", stateShort: "TN" },
  572: { code: 572, name: "Dindigul", stateName: "Tamil Nadu", stateShort: "TN" },
  573: { code: 573, name: "Erode", stateName: "Tamil Nadu", stateShort: "TN" },
  574: { code: 574, name: "Kancheepuram", stateName: "Tamil Nadu", stateShort: "TN" },
  575: { code: 575, name: "Kanniyakumari", stateName: "Tamil Nadu", stateShort: "TN" },
  576: { code: 576, name: "Karur", stateName: "Tamil Nadu", stateShort: "TN" },
  577: { code: 577, name: "Krishnagiri", stateName: "Tamil Nadu", stateShort: "TN" },
  578: { code: 578, name: "Madurai", stateName: "Tamil Nadu", stateShort: "TN" },
  579: { code: 579, name: "Nagapattinam", stateName: "Tamil Nadu", stateShort: "TN" },
  580: { code: 580, name: "Namakkal", stateName: "Tamil Nadu", stateShort: "TN" },
  581: { code: 581, name: "Perambalur", stateName: "Tamil Nadu", stateShort: "TN" },
  582: { code: 582, name: "Pudukkottai", stateName: "Tamil Nadu", stateShort: "TN" },
  583: { code: 583, name: "Ramanathapuram", stateName: "Tamil Nadu", stateShort: "TN" },
  584: { code: 584, name: "Salem", stateName: "Tamil Nadu", stateShort: "TN" },
  585: { code: 585, name: "Sivaganga", stateName: "Tamil Nadu", stateShort: "TN" },
  586: { code: 586, name: "Thanjavur", stateName: "Tamil Nadu", stateShort: "TN" },
  587: { code: 587, name: "The Nilgiris", stateName: "Tamil Nadu", stateShort: "TN" },
  588: { code: 588, name: "Theni", stateName: "Tamil Nadu", stateShort: "TN" },
  589: { code: 589, name: "Thiruvallur", stateName: "Tamil Nadu", stateShort: "TN" },
  590: { code: 590, name: "Thiruvarur", stateName: "Tamil Nadu", stateShort: "TN" },
  591: { code: 591, name: "Tiruchirappalli", stateName: "Tamil Nadu", stateShort: "TN" },
  592: { code: 592, name: "Tirunelveli", stateName: "Tamil Nadu", stateShort: "TN" },
  593: { code: 593, name: "Tiruvannamalai", stateName: "Tamil Nadu", stateShort: "TN" },
  594: { code: 594, name: "Thoothukkudi", stateName: "Tamil Nadu", stateShort: "TN" },
  595: { code: 595, name: "Vellore", stateName: "Tamil Nadu", stateShort: "TN" },
  596: { code: 596, name: "Viluppuram", stateName: "Tamil Nadu", stateShort: "TN" },
  597: { code: 597, name: "Virudhunagar", stateName: "Tamil Nadu", stateShort: "TN" },
  598: { code: 598, name: "Karaikal", stateName: "Puducherry", stateShort: "PY" },
  600: { code: 600, name: "Puducherry", stateName: "Puducherry", stateShort: "PY" },
  602: { code: 602, name: "South Andamans", stateName: "Andaman And Nicobar Islands", stateShort: "AN" },
  603: { code: 603, name: "Nicobars", stateName: "Andaman And Nicobar Islands", stateShort: "AN" },
  604: { code: 604, name: "Nuh", stateName: "Haryana", stateShort: "HR" },
  605: { code: 605, name: "Barnala", stateName: "Punjab", stateShort: "PB" },
  606: { code: 606, name: "Khunti", stateName: "Jharkhand", stateShort: "JH" },
  607: { code: 607, name: "Ramgarh", stateName: "Jharkhand", stateShort: "JH" },
  608: { code: 608, name: "S.A.S Nagar", stateName: "Punjab", stateShort: "PB" },
  609: { code: 609, name: "Tarn Taran", stateName: "Punjab", stateShort: "PB" },
  610: { code: 610, name: "Ariyalur", stateName: "Tamil Nadu", stateShort: "TN" },
  611: { code: 611, name: "Arwal", stateName: "Bihar", stateShort: "BR" },
  612: { code: 612, name: "Chirang", stateName: "Assam", stateShort: "AS" },
  613: { code: 613, name: "Peren", stateName: "Nagaland", stateShort: "NL" },
  614: { code: 614, name: "Kiphire", stateName: "Nagaland", stateShort: "NL" },
  615: { code: 615, name: "Longleng", stateName: "Nagaland", stateShort: "NL" },
  616: { code: 616, name: "Baksa", stateName: "Assam", stateShort: "AS" },
  617: { code: 617, name: "Udalguri", stateName: "Assam", stateShort: "AS" },
  618: { code: 618, name: "Kamrup Metro", stateName: "Assam", stateShort: "AS" },
  619: { code: 619, name: "Palwal", stateName: "Haryana", stateShort: "HR" },
  620: { code: 620, name: "Kishtwar", stateName: "Jammu And Kashmir", stateShort: "JK" },
  621: { code: 621, name: "Ramban", stateName: "Jammu And Kashmir", stateShort: "JK" },
  622: { code: 622, name: "Kulgam", stateName: "Jammu And Kashmir", stateShort: "JK" },
  623: { code: 623, name: "Bandipora", stateName: "Jammu And Kashmir", stateShort: "JK" },
  624: { code: 624, name: "Samba", stateName: "Jammu And Kashmir", stateShort: "JK" },
  625: { code: 625, name: "Shopian", stateName: "Jammu And Kashmir", stateShort: "JK" },
  626: { code: 626, name: "Ganderbal", stateName: "Jammu And Kashmir", stateShort: "JK" },
  627: { code: 627, name: "Reasi", stateName: "Jammu And Kashmir", stateShort: "JK" },
  628: { code: 628, name: "Anjaw", stateName: "Arunachal Pradesh", stateShort: "AR" },
  629: { code: 629, name: "Pratapgarh", stateName: "Rajasthan", stateShort: "RJ" },
  630: { code: 630, name: "Chikkaballapura", stateName: "Karnataka", stateShort: "KA" },
  631: { code: 631, name: "Bengaluru South", stateName: "Karnataka", stateShort: "KA" },
  632: { code: 632, name: "North And Middle Andaman", stateName: "Andaman And Nicobar Islands", stateShort: "AN" },
  633: { code: 633, name: "Kasganj", stateName: "Uttar Pradesh", stateShort: "UP" },
  634: { code: 634, name: "Tiruppur", stateName: "Tamil Nadu", stateShort: "TN" },
  635: { code: 635, name: "Yadgir", stateName: "Karnataka", stateShort: "KA" },
  636: { code: 636, name: "Bijapur", stateName: "Chhattisgarh", stateShort: "CG" },
  637: { code: 637, name: "Narayanpur", stateName: "Chhattisgarh", stateShort: "CG" },
  638: { code: 638, name: "Singrauli", stateName: "Madhya Pradesh", stateShort: "MP" },
  639: { code: 639, name: "Alirajpur", stateName: "Madhya Pradesh", stateShort: "MP" },
  640: { code: 640, name: "Amethi", stateName: "Uttar Pradesh", stateShort: "UP" },
  641: { code: 641, name: "Tapi", stateName: "Gujarat", stateShort: "GJ" },
  642: { code: 642, name: "Sukma", stateName: "Chhattisgarh", stateShort: "CG" },
  643: { code: 643, name: "Kondagaon", stateName: "Chhattisgarh", stateShort: "CG" },
  644: { code: 644, name: "Balodabazar-Bhatapara", stateName: "Chhattisgarh", stateShort: "CG" },
  645: { code: 645, name: "Gariyaband", stateName: "Chhattisgarh", stateShort: "CG" },
  646: { code: 646, name: "Balod", stateName: "Chhattisgarh", stateShort: "CG" },
  647: { code: 647, name: "Mungeli", stateName: "Chhattisgarh", stateShort: "CG" },
  648: { code: 648, name: "Surajpur", stateName: "Chhattisgarh", stateShort: "CG" },
  649: { code: 649, name: "Balrampur-Ramanujganj", stateName: "Chhattisgarh", stateShort: "CG" },
  650: { code: 650, name: "Bemetara", stateName: "Chhattisgarh", stateShort: "CG" },
  651: { code: 651, name: "Fazilka", stateName: "Punjab", stateShort: "PB" },
  652: { code: 652, name: "Khowai", stateName: "Tripura", stateShort: "TR" },
  653: { code: 653, name: "Sepahijala", stateName: "Tripura", stateShort: "TR" },
  654: { code: 654, name: "Gomati", stateName: "Tripura", stateShort: "TR" },
  655: { code: 655, name: "Unakoti", stateName: "Tripura", stateShort: "TR" },
  656: { code: 656, name: "North Garo Hills", stateName: "Meghalaya", stateShort: "ML" },
  657: { code: 657, name: "East Jaintia Hills", stateName: "Meghalaya", stateShort: "ML" },
  658: { code: 658, name: "South West Khasi Hills", stateName: "Meghalaya", stateShort: "ML" },
  659: { code: 659, name: "Sambhal", stateName: "Uttar Pradesh", stateShort: "UP" },
  660: { code: 660, name: "Shamli", stateName: "Uttar Pradesh", stateShort: "UP" },
  661: { code: 661, name: "Hapur", stateName: "Uttar Pradesh", stateShort: "UP" },
  662: { code: 662, name: "Pathankot", stateName: "Punjab", stateShort: "PB" },
  663: { code: 663, name: "South West Garo Hills", stateName: "Meghalaya", stateShort: "ML" },
  664: { code: 664, name: "Alipurduar", stateName: "West Bengal", stateShort: "WB" },
  665: { code: 665, name: "Palghar", stateName: "Maharashtra", stateShort: "MH" },
  666: { code: 666, name: "Longding", stateName: "Arunachal Pradesh", stateShort: "AR" },
  667: { code: 667, name: "Agar-Malwa", stateName: "Madhya Pradesh", stateShort: "MP" },
  668: { code: 668, name: "Chhotaudepur", stateName: "Gujarat", stateShort: "GJ" },
  669: { code: 669, name: "Mahisagar", stateName: "Gujarat", stateShort: "GJ" },
  670: { code: 670, name: "South East", stateName: "Delhi", stateShort: "DL" },
  672: { code: 672, name: "Arvalli", stateName: "Gujarat", stateShort: "GJ" },
  673: { code: 673, name: "Morbi", stateName: "Gujarat", stateShort: "GJ" },
  674: { code: 674, name: "Devbhumi Dwarka", stateName: "Gujarat", stateShort: "GJ" },
  675: { code: 675, name: "Gir Somnath", stateName: "Gujarat", stateShort: "GJ" },
  676: { code: 676, name: "Botad", stateName: "Gujarat", stateShort: "GJ" },
  677: { code: 677, name: "Kra Daadi", stateName: "Arunachal Pradesh", stateShort: "AR" },
  678: { code: 678, name: "Namsai", stateName: "Arunachal Pradesh", stateShort: "AR" },
  679: { code: 679, name: "Siang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  680: { code: 680, name: "Nirmal", stateName: "Telangana", stateShort: "TS" },
  681: { code: 681, name: "Jagitial", stateName: "Telangana", stateShort: "TS" },
  682: { code: 682, name: "Peddapalli", stateName: "Telangana", stateShort: "TS" },
  683: { code: 683, name: "Rajanna Sircilla", stateName: "Telangana", stateShort: "TS" },
  684: { code: 684, name: "Mancherial", stateName: "Telangana", stateShort: "TS" },
  685: { code: 685, name: "Kamareddy", stateName: "Telangana", stateShort: "TS" },
  686: { code: 686, name: "Hanumakonda", stateName: "Telangana", stateShort: "TS" },
  687: { code: 687, name: "Jayashankar Bhupalapally", stateName: "Telangana", stateShort: "TS" },
  688: { code: 688, name: "Mahabubabad", stateName: "Telangana", stateShort: "TS" },
  689: { code: 689, name: "Jangoan", stateName: "Telangana", stateShort: "TS" },
  690: { code: 690, name: "Bhadradri Kothagudem", stateName: "Telangana", stateShort: "TS" },
  691: { code: 691, name: "Sangareddy", stateName: "Telangana", stateShort: "TS" },
  692: { code: 692, name: "Siddipet", stateName: "Telangana", stateShort: "TS" },
  693: { code: 693, name: "Wanaparthy", stateName: "Telangana", stateShort: "TS" },
  694: { code: 694, name: "Nagarkurnool", stateName: "Telangana", stateShort: "TS" },
  695: { code: 695, name: "Jogulamba Gadwal", stateName: "Telangana", stateShort: "TS" },
  696: { code: 696, name: "Suryapet", stateName: "Telangana", stateShort: "TS" },
  697: { code: 697, name: "Yadadri Bhuvanagiri", stateName: "Telangana", stateShort: "TS" },
  698: { code: 698, name: "Vikarabad", stateName: "Telangana", stateShort: "TS" },
  699: { code: 699, name: "Kumuram Bheem Asifabad", stateName: "Telangana", stateShort: "TS" },
  700: { code: 700, name: "Medchal Malkajgiri", stateName: "Telangana", stateShort: "TS" },
  701: { code: 701, name: "Charkhi Dadri", stateName: "Haryana", stateShort: "HR" },
  702: { code: 702, name: "Kalimpong", stateName: "West Bengal", stateShort: "WB" },
  703: { code: 703, name: "Jhargram", stateName: "West Bengal", stateShort: "WB" },
  704: { code: 704, name: "Paschim Bardhaman", stateName: "West Bengal", stateShort: "WB" },
  705: { code: 705, name: "Biswanath", stateName: "Assam", stateShort: "AS" },
  706: { code: 706, name: "Majuli", stateName: "Assam", stateShort: "AS" },
  707: { code: 707, name: "South Salmara Mancachar", stateName: "Assam", stateShort: "AS" },
  708: { code: 708, name: "Charaideo", stateName: "Assam", stateShort: "AS" },
  709: { code: 709, name: "Hojai", stateName: "Assam", stateShort: "AS" },
  710: { code: 710, name: "West Karbi Anglong", stateName: "Assam", stateShort: "AS" },
  711: { code: 711, name: "Kakching", stateName: "Manipur", stateShort: "MN" },
  712: { code: 712, name: "Kangpokpi", stateName: "Manipur", stateShort: "MN" },
  713: { code: 713, name: "Jiribam", stateName: "Manipur", stateShort: "MN" },
  714: { code: 714, name: "Noney", stateName: "Manipur", stateShort: "MN" },
  715: { code: 715, name: "Pherzawl", stateName: "Manipur", stateShort: "MN" },
  716: { code: 716, name: "Tengnoupal", stateName: "Manipur", stateShort: "MN" },
  717: { code: 717, name: "Kamjong", stateName: "Manipur", stateShort: "MN" },
  718: { code: 718, name: "Kamle", stateName: "Arunachal Pradesh", stateShort: "AR" },
  719: { code: 719, name: "Lower Siang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  720: { code: 720, name: "Mulugu", stateName: "Telangana", stateShort: "TS" },
  721: { code: 721, name: "Narayanpet", stateName: "Telangana", stateShort: "TS" },
  722: { code: 722, name: "Niwari", stateName: "Madhya Pradesh", stateShort: "MP" },
  723: { code: 723, name: "Pakke Kessang", stateName: "Arunachal Pradesh", stateShort: "AR" },
  724: { code: 724, name: "Leparada", stateName: "Arunachal Pradesh", stateShort: "AR" },
  725: { code: 725, name: "Shi Yomi", stateName: "Arunachal Pradesh", stateShort: "AR" },
  726: { code: 726, name: "Hnahthial", stateName: "Mizoram", stateShort: "MZ" },
  727: { code: 727, name: "Saitual", stateName: "Mizoram", stateShort: "MZ" },
  728: { code: 728, name: "Khawzawl", stateName: "Mizoram", stateShort: "MZ" },
  729: { code: 729, name: "Kallakurichi", stateName: "Tamil Nadu", stateShort: "TN" },
  730: { code: 730, name: "Chengalpattu", stateName: "Tamil Nadu", stateShort: "TN" },
  731: { code: 731, name: "Ranipet", stateName: "Tamil Nadu", stateShort: "TN" },
  732: { code: 732, name: "Tirupathur", stateName: "Tamil Nadu", stateShort: "TN" },
  733: { code: 733, name: "Tenkasi", stateName: "Tamil Nadu", stateShort: "TN" },
  734: { code: 734, name: "Gaurela-Pendra-Marwahi", stateName: "Chhattisgarh", stateShort: "CG" },
  735: { code: 735, name: "Mayiladuthurai", stateName: "Tamil Nadu", stateShort: "TN" },
  736: { code: 736, name: "Noklak", stateName: "Nagaland", stateShort: "NL" },
  737: { code: 737, name: "Malerkotla", stateName: "Punjab", stateShort: "PB" },
  738: { code: 738, name: "Vijayanagara", stateName: "Karnataka", stateShort: "KA" },
  739: { code: 739, name: "Bajali", stateName: "Assam", stateShort: "AS" },
  740: { code: 740, name: "Eastern West Khasi Hills", stateName: "Meghalaya", stateShort: "ML" },
  741: { code: 741, name: "Pakyong", stateName: "Sikkim", stateShort: "SK" },
  742: { code: 742, name: "Soreng", stateName: "Sikkim", stateShort: "SK" },
  743: { code: 743, name: "Parvathipuram Manyam", stateName: "Andhra Pradesh", stateShort: "AP" },
  744: { code: 744, name: "Anakapalli", stateName: "Andhra Pradesh", stateShort: "AP" },
  745: { code: 745, name: "Alluri Sitharama Raju", stateName: "Andhra Pradesh", stateShort: "AP" },
  746: { code: 746, name: "Kakinada", stateName: "Andhra Pradesh", stateShort: "AP" },
  747: { code: 747, name: "Dr. B.R. Ambedkar Konaseema", stateName: "Andhra Pradesh", stateShort: "AP" },
  748: { code: 748, name: "Eluru", stateName: "Andhra Pradesh", stateShort: "AP" },
  749: { code: 749, name: "Ntr", stateName: "Andhra Pradesh", stateShort: "AP" },
  750: { code: 750, name: "Bapatla", stateName: "Andhra Pradesh", stateShort: "AP" },
  751: { code: 751, name: "Palnadu", stateName: "Andhra Pradesh", stateShort: "AP" },
  752: { code: 752, name: "Tirupati", stateName: "Andhra Pradesh", stateShort: "AP" },
  753: { code: 753, name: "Annamayya", stateName: "Andhra Pradesh", stateShort: "AP" },
  754: { code: 754, name: "Sri Sathya Sai", stateName: "Andhra Pradesh", stateShort: "AP" },
  755: { code: 755, name: "Nandyal", stateName: "Andhra Pradesh", stateShort: "AP" },
  756: { code: 756, name: "Tamulpur", stateName: "Assam", stateShort: "AS" },
  757: { code: 757, name: "Tseminyu", stateName: "Nagaland", stateShort: "NL" },
  758: { code: 758, name: "Chumoukedima", stateName: "Nagaland", stateShort: "NL" },
  759: { code: 759, name: "Khairagarh-Chhuikhadan-Gandai", stateName: "Chhattisgarh", stateShort: "CG" },
  760: { code: 760, name: "Manendragarh-Chirmiri-Bharatpur(M C B)", stateName: "Chhattisgarh", stateShort: "CG" },
  761: { code: 761, name: "Mohla-Manpur-Ambagarh Chouki", stateName: "Chhattisgarh", stateShort: "CG" },
  762: { code: 762, name: "Sakti", stateName: "Chhattisgarh", stateShort: "CG" },
  763: { code: 763, name: "Sarangarh-Bilaigarh", stateName: "Chhattisgarh", stateShort: "CG" },
  764: { code: 764, name: "Niuland", stateName: "Nagaland", stateShort: "NL" },
  765: { code: 765, name: "Shamator", stateName: "Nagaland", stateShort: "NL" },
  766: { code: 766, name: "MAUGANJ", stateName: "Madhya Pradesh", stateShort: "MP" },
  767: { code: 767, name: "Deeg", stateName: "Rajasthan", stateShort: "RJ" },
  768: { code: 768, name: "Didwana-Kuchaman", stateName: "Rajasthan", stateShort: "RJ" },
  770: { code: 770, name: "Khairthal-Tijara", stateName: "Rajasthan", stateShort: "RJ" },
  772: { code: 772, name: "Phalodi", stateName: "Rajasthan", stateShort: "RJ" },
  774: { code: 774, name: "Beawar", stateName: "Rajasthan", stateShort: "RJ" },
  775: { code: 775, name: "Balotra", stateName: "Rajasthan", stateShort: "RJ" },
  777: { code: 777, name: "Salumbar", stateName: "Rajasthan", stateShort: "RJ" },
  782: { code: 782, name: "Kotputli-Behror", stateName: "Rajasthan", stateShort: "RJ" },
  784: { code: 784, name: "Maihar", stateName: "Madhya Pradesh", stateShort: "MP" },
  785: { code: 785, name: "Pandhurna", stateName: "Madhya Pradesh", stateShort: "MP" },
  786: { code: 786, name: "Keyi Panyor", stateName: "Arunachal Pradesh", stateShort: "AR" },
  787: { code: 787, name: "Bichom", stateName: "Arunachal Pradesh", stateShort: "AR" },
  788: { code: 788, name: "Meluri", stateName: "Nagaland", stateShort: "NL" },
  789: { code: 789, name: "Vav-Tharad", stateName: "Gujarat", stateShort: "GJ" },
  790: { code: 790, name: "Markapuram", stateName: "Andhra Pradesh", stateShort: "AP" },
  791: { code: 791, name: "Polavaram", stateName: "Andhra Pradesh", stateShort: "AP" },
  792: { code: 792, name: "Hansi", stateName: "Haryana", stateShort: "HR" },
  793: { code: 793, name: "Kushavati", stateName: "Goa", stateShort: "GA" },
  794: { code: 794, name: "Outer North", stateName: "Delhi", stateShort: "DL" },
  795: { code: 795, name: "Old Delhi", stateName: "Delhi", stateShort: "DL" },
  796: { code: 796, name: "Central North", stateName: "Delhi", stateShort: "DL" },
};

export const DISTRICT_COUNT = 784;
